<a href="https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb" target="_blank">100 Numpy exercises</a><br>
<a href="https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_hints_with_solutions.md" target="_blank">100 Numpy exercises with hints with solutions</a><br>
<a href="https://osawat.hatenablog.com/entry/2018/12/24/044047" target="_blank">numpy-100 日本語翻訳</a><br>

In [1]:
import numpy as np

In [2]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.random.random((3, 3, 3))

array([[[0.29926116, 0.7910454 , 0.25811506],
        [0.51241473, 0.68979068, 0.82009666],
        [0.81493489, 0.2686393 , 0.79155489]],

       [[0.63692286, 0.38332947, 0.02492294],
        [0.16803183, 0.56058021, 0.6025839 ],
        [0.97259758, 0.24798552, 0.55897084]],

       [[0.87766534, 0.51875953, 0.31395618],
        [0.99646041, 0.73642003, 0.6466979 ],
        [0.50805652, 0.06715471, 0.17618305]]])

In [5]:
arr = np.random.random((10, 10))
print(arr.min(), arr.max())

0.00579500108758868 0.9943275286591032


In [6]:
np.random.random(30).mean()

0.5338005496459632

In [7]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
z = np.ones((5,5))
np.pad(z, [1, 1])

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [10]:
np.diag([1,2,3,4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [11]:
# x = np.tile([0, 1], 4)
# y = np.tile([1, 0], 4)
# xy = np.ravel(np.concatenate((x, y)))
# xy
# z = np.tile(xy, 4).reshape((8, 8))
# z
z = np.zeros((8,8),dtype=int)
z[1::2, 0::2] = 1
z[0::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [12]:
np.arange(1, 337).reshape((6, 7, 8))[1, 5, 3]
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [13]:
# 21. Create a checkerboard 8x8 matrix using the tile function
z = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [14]:
z = np.random.random((5, 5))
z = (z - z.mean()) / z.std()
z

array([[ 0.20592533, -0.0723239 ,  0.11434067,  0.73327512, -0.7325839 ],
       [ 1.13252997, -0.13644711,  1.27550629,  0.26317881,  0.71376015],
       [ 0.38417206, -1.03104811, -1.89058667,  0.81906406, -1.70362871],
       [-0.3928042 ,  1.1545136 ,  0.58713436, -0.90739097, -0.03239873],
       [ 0.0094665 , -1.13554912,  1.47161321, -2.07980765,  1.25008896]])

In [15]:
c = np.dtype([('r', np.ubyte, 1),
              ('g', np.ubyte, 1),
              ('b', np.ubyte, 1),
              ('a', np.ubyte, 1)])
c

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [16]:
x = np.random.random((5, 3))
y = np.random.random((3, 2))
np.dot(x, y)

array([[0.85713052, 0.74430058],
       [0.43630125, 0.61938189],
       [0.852288  , 0.91063147],
       [1.27165062, 1.38211293],
       [0.94952006, 1.07360304]])

In [17]:
x = np.arange(1, 11)
y = x.reshape((2, 5))

def change_ele(z):
    if z.ndim == 1:
        z = np.where((z >= 3) & (z <= 8), z*(-1), z)
    return z
    
for z in [x, y]:
    print(change_ele(z))
#     z[(z>=3) & (z<=8)] *= -1
#     print(z)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [18]:
# print(sum(range(5),-1))
# from numpy import *
print(sum(range(5),-1))

9


In [19]:
Z = np.arange(0, 10)
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

In [21]:
z = np.random.uniform(-10,+10,10)
print(z)
print(np.copysign(np.ceil(np.abs(z)), z))

[ 6.01910272 -1.52217724  5.34628505  2.28369013 -6.42041521  7.03811536
 -9.76459589  6.32718639  8.42416169  6.86223822]
[  7.  -2.   6.   3.  -7.   8. -10.   7.   9.   7.]


In [22]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(z1, z2)
print(set(z1) & set(z2))
print(np.intersect1d(z1, z2))

[8 3 7 6 8 3 4 9 4 9] [2 2 4 8 8 5 1 9 7 6]
{4, 6, 7, 8, 9}
[4 6 7 8 9]


In [23]:
z = np.arange(10)
%timeit np.add.reduce(z)
%timeit z.sum()

1.76 µs ± 63 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.12 µs ± 275 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [24]:
np.add.reduce(z)

45

In [25]:
x = np.random.random(size=10)
y = np.random.random(size=10)
print(np.allclose(x, y))
print(np.array_equal(x, y))

False
False


In [26]:
x = np.arange(0, 10)
x.flags.writeable = False
np.append(x, 0.1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
radian = np.sqrt(x**2 + y**2)
theta = np.arctan2(x, y)
print('radian:\t', radian)
print('theta:\t', theta)

import matplotlib.pyplot as plt

# 直交系グラフ
ax1 = plt.subplot(1,2,1)
ax1.scatter(x,y)
ax1.axis([0,1,0,1])
ax1.grid(True)
ax1.set_aspect('equal')

# 極座標系グラフ
ax2 = plt.subplot(1,2,2,polar=True)
ax2.scatter(theta,radian)
ax2.set_rmax(1)
ax2.grid(True)
plt.show()

radian:	 [1.25474508 0.68636572 0.44422195 0.77016688 1.22921069 1.05559202
 0.25454383 0.8575416  0.93136351 0.4089062 ]
theta:	 [0.85888778 0.98484202 1.09524476 0.572465   0.76381445 0.98274777
 0.29106468 0.45174016 0.62950797 0.97415389]


<Figure size 640x480 with 2 Axes>

In [28]:
x = np.random.random(10)
x[x.argmax()] = 0
x

array([0.24523277, 0.        , 0.35344046, 0.85371473, 0.24913828,
       0.29128491, 0.45629707, 0.45058208, 0.43013086, 0.51289541])

In [29]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [30]:
x = np.arange(8)
y = x + 0.5
c = 1 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.1636371179666


In [31]:
# 48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    print('\n')

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    print('\n')

-128
127


-2147483648
2147483647


-9223372036854775808
9223372036854775807


-3.4028235e+38
3.4028235e+38
1.1920929e-07


-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16




In [32]:
import sys
np.set_printoptions(threshold=sys.maxsize)
#_printoptions(threshold=np.nan)
z = np.zeros((20, 20))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [33]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print(z[index])

13


In [34]:
z = np.zeros(10, [('position', [('x', float, 1),
                               ('y', float, 1)]),
                 ('color', [('r', float, 1),
                            ('g', float, 1),
                            ('b', float, 1)])])
z

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [35]:
z = np.random.random(size=(100, 2))
x, y = np.atleast_2d(z[:, 0], z[:, 1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
d

array([[0.        , 0.62420646, 0.87212008, 0.27476358, 0.6785026 ,
        0.22566452, 0.56435763, 0.45679953, 0.86269527, 1.0144956 ,
        0.65466561, 0.67832476, 0.8942436 , 0.57981732, 0.79970657,
        0.50073218, 0.85453916, 0.8314714 , 0.68728741, 0.6682793 ,
        0.83390422, 0.2207134 , 0.62731753, 0.57302453, 0.52334876,
        0.71653972, 0.73805065, 0.9589749 , 0.83921184, 0.07826712,
        0.80607644, 0.78937116, 0.62824703, 0.7454729 , 0.86602858,
        1.11689336, 0.97871813, 0.99804308, 0.1011741 , 0.37366906,
        0.76087714, 0.62484294, 0.825315  , 0.63485075, 0.57569555,
        1.0581428 , 0.59522722, 0.44649169, 0.65413023, 0.74251328,
        0.98400832, 0.83803529, 0.9312659 , 0.69087624, 0.74262593,
        0.49275923, 1.0012477 , 0.7655367 , 0.17974041, 0.08001474,
        0.99104686, 0.35293834, 0.30456029, 0.86484373, 0.85780312,
        0.8439245 , 0.8012732 , 0.54442126, 0.93273716, 0.24135217,
        0.85367905, 0.80144138, 0.28199746, 0.04

In [36]:
z = np.ones(10, dtype=float)
z.astype(dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
            6,  ,  , 7, 8\n
            ,  , 9,10,11""")

z = np.genfromtxt(s, delimiter=',', dtype=np.int, filling_values=0)
z

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  7,  8],
       [ 0,  0,  9, 10, 11]])

In [38]:
z = np.arange(1, 10).reshape((3, 3))

for idx, val in np.ndenumerate(z):
    print(*idx, val)
print('------')
for idx in np.ndindex(z.shape):
    print(*idx)

0 0 1
0 1 2
0 2 3
1 0 4
1 1 5
1 2 6
2 0 7
2 1 8
2 2 9
------
0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [39]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x**2 + y**2)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

In [40]:
n = 10
p = 3
z = np.zeros((n, n))
i, j = np.random.choice(n), np.random.choice(n)
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
x = np.random.rand(5, 10)
y = x.mean(axis=1, keepdims=True)
z = x - y.mean(axis=1).reshape(-1, 1)
z

array([[ 6.48297511e-02,  1.05252479e-01,  3.35854231e-01,
        -5.67763615e-01,  6.97299550e-02,  4.23291840e-02,
         2.53908623e-01,  1.75704256e-01, -2.88556064e-01,
        -1.91288802e-01],
       [-7.50008328e-02, -1.81460807e-01, -4.46016663e-01,
        -8.70511756e-02,  1.30402479e-01,  4.98712911e-02,
        -5.37086928e-05,  2.55071986e-01,  2.11496002e-01,
         1.42741430e-01],
       [ 2.26948820e-01,  4.34755968e-01, -5.43864798e-01,
         2.54133265e-01, -4.63925407e-01,  1.86701664e-01,
         3.45861002e-01, -9.81889067e-02, -4.74211767e-01,
         1.31790160e-01],
       [ 1.36268317e-01,  3.35048899e-01,  1.65948096e-01,
         4.69001180e-01, -3.11997354e-01, -8.79369922e-02,
        -1.36288872e-01,  7.37957606e-02, -4.97702292e-01,
        -1.46136742e-01],
       [-4.42887519e-01, -5.48902259e-01,  1.44143060e-01,
         2.84448747e-01, -1.01755924e-02, -2.96881186e-01,
         3.03947952e-01,  5.29026134e-02,  3.15654051e-01,
         1.

In [42]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[7 7 7]
 [3 8 0]
 [1 6 3]]
[[1 6 3]
 [7 7 7]
 [3 8 0]]


In [43]:
z = np.random.randint(0,3,(3,10))
print(z)
print((~z.any(axis=0)).any())

[[0 0 2 2 0 1 0 2 0 2]
 [1 0 1 0 0 0 1 0 2 0]
 [1 1 1 0 2 2 1 0 1 1]]
False


In [44]:
z = np.random.uniform(0,1,10)
n = 0.5
arg = np.abs(z-n).argmin()
print(z)
print(z[arg])

[0.25906312 0.92344217 0.4284632  0.8737469  0.19005121 0.00542341
 0.86427701 0.91000387 0.90048692 0.41875999]
0.42846320112987324


In [45]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)

it = np.nditer([a, b, None])
for x, y, z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [46]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [47]:
# Author: Brett Olsen
z = np.ones(10)
i = np.random.randint(0,len(z),20)
z += np.bincount(i, minlength=len(z))
print(z)
# Another solution
# Author: Bartosz Telenczuk
np.add.at(z, i, 1)
print(z)

[1. 5. 2. 1. 4. 3. 4. 6. 2. 2.]
[ 1.  9.  3.  1.  7.  5.  7. 11.  3.  3.]


In [48]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [49]:
# 66. 画像が (w, h, 3) (dtype=ubyte) のとき、ユニークな色の数を計算する
